name: Try Environment

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
  
jobs:
  test-env:
    name: Test Env
    environment: Prod
    runs-on: ubuntu-latest

    steps:
    - name: Check env
      run: |
        echo "${{ secrets.APP_KEY }}, ${{ vars.GCP_CLOUD_RUN_REGION }}"
        echo "GCP_CLOUD_RUN_REGION1=${{ vars.GCP_CLOUD_RUN_REGION }}" >> "$GITHUB_ENV"

    - name: Check env2
      run: |
        echo ${{ env.GCP_CLOUD_RUN_REGION1 }}
    
