name: Try Environment

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
  
jobs:
  test-env:
    name: Test Env
    environment: Prod
    runs-on: ubuntu-latest

    steps:
    - name: Check env
      run: |
        echo "${{ secrets.APP_KEY }}, ${{ vars.GCP_CLOUD_RUN_REGION }}"
    
